## If and elif

We have seen the working of an 'if' statement in the previous video unit. Let us go through it once again.

In python, the syntax for an ‘if' conditional statement is as follows:

<pre>if (condition_1):<br>
    statement_block_1<br>
elif (condition_2):<br>
    statement_block_2<br>
elif (condition_3):<br>
    statement_block_3<br></pre>
<br>
Let us consider an example to understand the working of an 'if' statement.

In [1]:
stock_price_ABC = 299  # Variable value

if (stock_price_ABC < 300):  # if condition_1 is true then...
    # statement_block_1 will get executed
    print("We will buy 500 shares of ABC")

elif (stock_price_ABC == 300):
    print("We will buy 200 shares of ABC")

elif (stock_price_ABC > 300):
    print("We will buy 150 shares of ABC")

We will buy 500 shares of ABC

If you change the value of the variable 'stock_price_ABC' to...

In [4]:
stock_price_ABC = 301  # then...

if (stock_price_ABC < 300):
    print("We will buy 500 shares of ABC")

elif (stock_price_ABC == 300):
    print("We will buy 200 shares of ABC")

elif (stock_price_ABC > 300):  # if condition_3 is true then...
    # statement_block_3 will get executed
    print("We will buy 150 shares of ABC")

We will buy 150 shares of ABC

## If and else 

If - else block of conditional statements is similar to the working of 'if' statements. If the 'if' condition is <b>true</b>, then the statements inside the 'if' block will be executed. If the 'if' condition is <b> false</b>, then the statements inside the 'else' block will be executed. 

In Python, the syntax for an ‘if else' conditional statement is as follows:

<pre>if (condition_1):<br>
    statement_block_1<br>
else:<br>
    statement_block_2<br></pre>
<br>
Let us consider an example to understand the working of an 'if else' statement.

In [5]:
stock_price_ABC = 300

if (stock_price_ABC > 250):  # if condition 1 is true then....
    # this block of code will be executed
    print("We will sell the stock and book the profit")

else:
    print("We will keep buying the stock")

We will sell the stock and book the profit

If you change the value of the variable 'stock_price_ABC' to...

In [7]:
stock_price_ABC = 200  # then...

if (stock_price_ABC > 250):  # if condition 1 is false then....
    print("We will sell the stock and book the profit")

else:
    # this block of code will be executed
    print(" We will keep buying the stock")

 We will keep buying the stock

In the upcoming IPython Notebook, we will understand about <b>Loops.</b> <br><br>

## For loop

In the programming languages, there are many situations when you need to execute a block of code several numbers of times. A loop statement allows us to execute a statement or group of statements multiple times.

The general syntax for a ‘for’ loop is as follows: 

<pre>
<b>for (variable) in <b>sequence:
    block of statements</b>
</pre>

Here, the block of statements within the loop will get executed, until all ‘sequence’ elements get exhausted. Once all sequence elements are exhausted, the program will come out of the loop.

In [ ]:
if (stock_price_ABC < 300):
    print ('We will buy 500 shares of ABC')

In [8]:
# Closing prices of the ABC stock over 10 days

Close_Price_ABC = [300, 305, 287, 298, 335,
                   300, 297, 300, 295, 310]  # Our sequence

for i in Close_Price_ABC:

    if i < 300:
        print("We Buy")

    if i == 300:
        print("No new positions")

    if i > 300:
        print("We Sell")

print("We are now out of the loop")

No new positions
We Sell
We Buy
We Buy
We Sell
No new positions
We Buy
No new positions
We Buy
We Sell
We are now out of the loop

Here, the output is what was discussed in the previous video unit.<br>
<br>
The variable ‘i’ first stores the value ‘300’ in it and runs it through the loop to execute the statements. Here, we have placed a condition that if ‘i == 300’ we will print “No new positions”. Hence, as you can see, this is the first statement in our output.<br>
<br>
Now, ‘i’ will run through the sequence and pick the second element of the sequence which is ‘305’. It will run it through the statements of the loop. When i = 305, it will execute the block where ‘if i > 300: print (“We Sell”). Check the second output.<br>
<br>
Similarly, it will keep executing all the elements of the loop. Observe the output.

In [12]:
import numpy as np
import pandas as pd

infy = pd.read_csv('Quote-FAO-INFY-10-05-2021-to-16-06-2021.csv')
infy

# We have delibrately taken a smaller dataframe to understand the output.
# You may experiment using bigger dataframes to understand the power of 'for' loop

,DATE,EXPIRY DATE,OPTION TYPE,STRIKE PRICE,OPEN PRICE,HIGH PRICE,LOW PRICE,CLOSE PRICE,LAST PRICE,SETTLE PRICE,Volume,VALUE,PREMIUM VALUE,OPEN INTEREST,CHANGE IN OI
0,27-May-2021,27-May-2021,XX,-,"1,399.65","1,416.10","1,393.85","1,401.85","1,409.80","1,402.25",8118600,"11,434,824,630.00","11,434,824,630.00",798600,-4577400.0
1,26-May-2021,27-May-2021,XX,-,"1,367.90","1,402.45","1,362.85","1,397.25","1,396.65","1,397.25",10971600,"15,206,670,600.00","15,206,670,600.00",5376000,-6024000.0
2,25-May-2021,27-May-2021,XX,-,"1,358.35","1,369.80","1,357.40","1,363.80","1,364.75","1,363.80",10751400,"14,667,563,880.00","14,667,563,880.00",11400000,-6187800.0
3,24-May-2021,27-May-2021,XX,-,"1,365.00","1,366.70","1,348.50","1,351.80","1,352.30","1,351.80",9763200,"13,244,745,090.00","13,244,745,090.00",17587800,-5164200.0
4,21-May-2021,27-May-2021,XX,-,"1,352.00","1,362.00","1,351.00","1,359.55","1,360.50","1,359.55",8689200,"11,784,160,200.00","11,784,160,200.00",22752000,-3121200.0
5,20-May-2021,27-May-2021,XX,-,"1,350.35","1,351.85","1,339.05","1,344.00","1,344.70","1,344.00",4708200,"6,330,915,930.00","6,330,915,930.00",25873200,-967200.0
6,19-May-2021,27-May-2021,XX,-,"1,344.75","1,361.60","1,337.20","1,342.80","1,341.45","1,342.80",5961000,"8,055,166,920.00","8,055,166,920.00",26840400,-695400.0
7,18-May-2021,27-May-2021,XX,-,"1,339.95","1,350.30","1,336.20","1,345.95","1,344.80","1,345.95",8112600,"10,905,840,480.00","10,905,840,480.00",27535800,-1411800.0
8,17-May-2021,27-May-2021,XX,-,"1,324.00","1,336.55","1,324.00","1,334.15","1,334.25","1,334.15",5094000,"6,782,717,490.00","6,782,717,490.00",28947600,-851400.0
9,14-May-2021,27-May-2021,XX,-,"1,328.20","1,331.60","1,313.05","1,320.60","1,321.05","1,320.60",6025800,"7,948,959,780.00","7,948,959,780.00",29799000,-127800.0
10,12-May-2021,27-May-2021,XX,-,"1,333.00","1,335.25","1,316.95","1,329.00","1,329.00","1,329.00",6780600,"8,989,680,360.00","8,989,680,360.00",29926800,-354000.0
11,11-May-2021,27-May-2021,XX,-,"1,342.95","1,348.00","1,331.50","1,337.15","1,338.45","1,337.15",7114800,"9,517,193,760.00","9,517,193,760.00",30280800,723600.0
12,10-May-2021,27-May-2021,XX,-,"1,356.15","1,359.00","1,343.10","1,347.35","1,347.75","1,347.35",6470400,"8,730,236,250.00","8,730,236,250.00",29557200,572400.0

In [16]:
# We will just take the 'Close Price' column to run the 'for' loop

for i in range(len(infy)):

    if (infy.iloc[i]["Volume "] < 4708200):
        print("We buy")

    elif ((infy.iloc[i]["Volume "] > 4708200) & (infy.iloc[i]["Volume "] < 5708200)):
        print("We do nothing")

    elif (infy.iloc[i]["Volume "] > 5708200):
        print("We Sell")

We Sell
We Sell
We Sell
We Sell
We Sell
We Sell
We Sell
We do nothing
We Sell
We Sell
We Sell
We Sell

## While loop

(Optional Read)

The while construct consists of a condition and block of code. 

The general syntax for a ‘while’ loop is as follows: 

<pre>
<b> while condition/expression:
    block of statements</b>
</pre>

To begin, the condition is evaluated.<br>
<br>
If the condition is true, the 'block of statements' is executed. Every time, the condition is checked before executing the block of statements. <br>
<br>
This keeps on repeating until the condition becomes false. Once the condition is false, it comes out of the loop to execute the other statements.

In [17]:
a = 0  # Variable

while a <= 10:  # This is the condition. The loop will execute until the condition becomes 'false'
    a = a + 1
    print(a)
print("We are now out of the loop")

1
2
3
4
5
6
7
8
9
10
11
We are now out of the loop

In [ ]:
Close_Price_ABC = [300,305,287,298,335,300,297,300,295,310] # Our sequence
# Type your codes here
for i in Close_Pricce_ABC:
    if (i < 300):
        print ("We Buy")